SELECT * FROM SUPFUNCIONARIO;
SELECT * FROM SUPDESCRICAO;
SELECT * FROM SUPMALOTE;

SELECT
    M.SEQCODMALOTE AS CodMalote,
    F.NOME AS NomeFuncionario,
    M.DTENVIO AS DataEnvioDoMalote,
    M.DTCONFERENCIA AS DataConferencia,
    D.DESCRICAO AS DescricaoSituacao
FROM SUPMALOTE M
JOIN SUPFUNCIONARIO F ON M.CODFUNCIONARIO = F.SEQCODFUNCIONARIO
JOIN SUPDESCRICAO D ON M.CODDESCRICAO = D.SEQCODDESCRICAO
ORDER BY M.SEQCODMALOTE;

SELECT D.DESCRICAO AS Situacao, COUNT(M.SEQCODMALOTE) AS Quantidade
FROM SUPMALOTE M
JOIN SUPDESCRICAO D ON M.CODDESCRICAO = D.SEQCODDESCRICAO
GROUP BY D.DESCRICAO
ORDER BY Quantidade DESC;

SELECT F.NOME AS Funcionario, COUNT(M.SEQCODMALOTE) AS TotalMalotesEnviados
FROM SUPMALOTE M
JOIN SUPFUNCIONARIO F ON M.CODFUNCIONARIO = F.SEQCODFUNCIONARIO
GROUP BY F.NOME
ORDER BY TotalMalotesEnviados DESC;
